name:                game-of-life
version:             0.1.0
github:              "Denikozub/game-of-life"
license:             BSD3
author:              "Voronin A., Kozub. D."
maintainer:          "denikozub@gmail.com"
copyright:           "2022 Kozub Denis"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Denikozub/game-of-life/blob/main/README.md>

dependencies:
- base >= 4.7 && < 5
- gloss

library:
  source-dirs: src

executables:
  game-of-life-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - game-of-life

tests:
  game-of-life-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - game-of-life
